server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead-authuser
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true